FROM mcr.microsoft.com/devcontainers/base:debian

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y --no-install-recommends build-essential clang ffmpeg && \
    ln -s /usr/lib/x86_64-linux-gnu/libopus.so.0 /usr/lib/

ENV UV_LINK_MODE=copy
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY --from=geldata/gel-cli:latest /usr/bin/gel /bin/
COPY --from=ghcr.io/japan7/gel-dump:latest gel.dump /
